-- ============================================
-- CÓDIGO27 - Supabase Database Setup
-- Ejecutar este SQL en Supabase Dashboard → SQL Editor
-- ============================================

-- 1. Tabla de Perfiles (extensión de auth.users)
CREATE TABLE IF NOT EXISTS perfiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  instagram_handle TEXT,
  rol TEXT CHECK (rol IN ('staff', 'admin')) DEFAULT 'staff',
  estado_cuenta TEXT CHECK (estado_cuenta IN ('pendiente', 'aprobado', 'rechazado')) DEFAULT 'pendiente',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de Publicaciones
CREATE TABLE IF NOT EXISTS publicaciones (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  titulo TEXT NOT NULL,
  cuerpo TEXT,
  formato TEXT CHECK (formato IN ('texto', 'video', 'audio')) NOT NULL,
  media_url TEXT,
  imagen_portada TEXT,
  estado TEXT CHECK (estado IN ('borrador', 'publicado', 'observado')) DEFAULT 'borrador',
  comentario_docente TEXT,
  estudiante_id UUID REFERENCES perfiles(id) ON DELETE SET NULL,
  autor_nombre_demo TEXT,
  total_reacciones INTEGER DEFAULT 0,
  fecha_publicacion TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabla de Reacciones (anónimas)
CREATE TABLE IF NOT EXISTS reacciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id UUID REFERENCES publicaciones(id) ON DELETE CASCADE NOT NULL,
  tipo TEXT CHECK (tipo IN ('interesa', 'enoja', 'alegra', 'entristece', 'piensa')) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Vista de Estadísticas de Impacto (para Admin)
CREATE OR REPLACE VIEW estadisticas_impacto AS
SELECT 
  p.estudiante_id,
  per.nombre || ' ' || per.apellido AS estudiante_nombre,
  p.formato,
  COUNT(r.id) AS total_reacciones,
  COUNT(CASE WHEN r.tipo = 'interesa' THEN 1 END) AS reacciones_interesa,
  COUNT(CASE WHEN r.tipo = 'enoja' THEN 1 END) AS reacciones_enoja,
  COUNT(CASE WHEN r.tipo = 'alegra' THEN 1 END) AS reacciones_alegra,
  COUNT(CASE WHEN r.tipo = 'entristece' THEN 1 END) AS reacciones_entristece,
  COUNT(CASE WHEN r.tipo = 'piensa' THEN 1 END) AS reacciones_piensa
FROM publicaciones p
LEFT JOIN reacciones r ON r.publicacion_id = p.id
LEFT JOIN perfiles per ON per.id = p.estudiante_id
WHERE p.estado = 'publicado'
GROUP BY p.estudiante_id, per.nombre, per.apellido, p.formato;

-- 5. Función para incrementar contador de reacciones
CREATE OR REPLACE FUNCTION incrementar_reaccion(pub_id UUID)
RETURNS void AS $$
BEGIN
  UPDATE publicaciones SET total_reacciones = total_reacciones + 1 WHERE id = pub_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Función para auto-crear perfil al registrarse
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO perfiles (id, nombre, apellido, rol, estado_cuenta)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nombre', split_part(COALESCE(NEW.email, ''), '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'apellido', ''),
    CASE WHEN NEW.email = 'yesicalp@gmail.com' THEN 'admin' ELSE 'staff' END,
    CASE WHEN NEW.email = 'yesicalp@gmail.com' THEN 'aprobado' ELSE 'pendiente' END
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para auto-crear perfil
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE publicaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE reacciones ENABLE ROW LEVEL SECURITY;

-- PERFILES: Lectura
CREATE POLICY "perfiles_select_own" ON perfiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "perfiles_select_admin" ON perfiles
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol = 'admin')
  );

-- PERFILES: Inserción (el trigger lo hace, pero por si acaso)
CREATE POLICY "perfiles_insert_own" ON perfiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- PERFILES: Actualización propia
CREATE POLICY "perfiles_update_own" ON perfiles
  FOR UPDATE USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- PERFILES: Admin puede actualizar cualquier perfil
CREATE POLICY "perfiles_update_admin" ON perfiles
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol = 'admin')
  );

-- PUBLICACIONES: Lectura pública (solo publicadas)
CREATE POLICY "publicaciones_select_published" ON publicaciones
  FOR SELECT USING (estado = 'publicado');

-- PUBLICACIONES: Staff lee sus propias (cualquier estado)
CREATE POLICY "publicaciones_select_own" ON publicaciones
  FOR SELECT USING (auth.uid() = estudiante_id);

-- PUBLICACIONES: Admin lee todas
CREATE POLICY "publicaciones_select_admin" ON publicaciones
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol = 'admin')
  );

-- PUBLICACIONES: Staff crea
CREATE POLICY "publicaciones_insert_staff" ON publicaciones
  FOR INSERT WITH CHECK (auth.uid() = estudiante_id);

-- PUBLICACIONES: Staff edita las suyas
CREATE POLICY "publicaciones_update_own" ON publicaciones
  FOR UPDATE USING (auth.uid() = estudiante_id);

-- PUBLICACIONES: Admin edita cualquiera
CREATE POLICY "publicaciones_update_admin" ON publicaciones
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol = 'admin')
  );

-- PUBLICACIONES: Staff elimina sus borradores
CREATE POLICY "publicaciones_delete_own_draft" ON publicaciones
  FOR DELETE USING (auth.uid() = estudiante_id AND estado = 'borrador');

-- PUBLICACIONES: Admin elimina cualquiera
CREATE POLICY "publicaciones_delete_admin" ON publicaciones
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM perfiles WHERE id = auth.uid() AND rol = 'admin')
  );

-- REACCIONES: Lectura pública
CREATE POLICY "reacciones_select_public" ON reacciones
  FOR SELECT USING (true);

-- REACCIONES: Inserción pública (anónimas)
CREATE POLICY "reacciones_insert_public" ON reacciones
  FOR INSERT WITH CHECK (true);

-- ============================================
-- ÍNDICES para rendimiento
-- ============================================
CREATE INDEX IF NOT EXISTS idx_publicaciones_estado ON publicaciones(estado);
CREATE INDEX IF NOT EXISTS idx_publicaciones_estudiante ON publicaciones(estudiante_id);
CREATE INDEX IF NOT EXISTS idx_publicaciones_fecha ON publicaciones(fecha_publicacion DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_reacciones_publicacion ON reacciones(publicacion_id);
